services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nestjs-drizzle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_2:/var/lib/postgresql/data

volumes:
  postgres_data_2:
